# Generated by Django 3.2.8 on 2021-10-18 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_order',
            name='id_food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.food'),
        ),
    ]
