# Generated by Django 3.2.8 on 2021-11-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_order_starttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='id_cus',
        ),
    ]
