# Generated by Django 3.2.8 on 2021-10-19 10:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_food_order_id_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='products.place'),
        ),
        migrations.AlterField(
            model_name='order',
            name='starttime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
